local _,FT=...
-- Short player-facing notes for the "What's new" window. Newest first.
FT.changelog={
    -- Each note: an icon (Interface\\Icons name), a short title and one short line.
    {version="0.30.0",notes={
        {icon="Spell_Nature_StoneSkinTotem",title="Totem circles",text="Show reliably for new and replaced totems, stay up in combat and go away when a totem does."},
        {icon="Spell_Fire_Fire",title="Fire sound removed",text="Standing in fire is out for now: it also went off on damage over time."},
    }},
    {version="0.20.0",notes={
        {icon="INV_Misc_Key_03",title="Spell binds",text="Bind spells, items and macros to keys without an action bar. Keybinds > Spell binds."},
        {icon="Ability_Kick",title="Role keys",text="Interrupt, taunt, heal, crowd control and more: the same key does the same job on every character."},
        {icon="INV_Misc_Book_09",title="Profiles save by themselves",text="No more \"Save changes?\": every change goes into your profile, with Undo if you need it."},
        {icon="INV_Misc_Note_01",title="Action bars in exports",text="Take your action bars, keybinds and spell binds to another character or computer."},
        {icon="Spell_Nature_TimeStop",title="Backups and restore",text="Your keybinds, action bars and spell binds are backed up before an import. Put any copy back."},
        {icon="Ability_Rogue_Sprint",title="Move from any window",text="A move button in every title bar; windows shrink while you move things."},
    }},
    {version="0.15.0",notes={
        {icon="INV_Misc_Coin_01",title="Classic gold look",text="Dark brown and gold instead of purple, and a clearer main menu."},
        {icon="Spell_Nature_StoneSkinTotem",title="Totem range",text="Shamans: see each totem's 30-yard reach on the minimap. Combat > Totems."},
        {icon="Racial_Orc_BerserkerStrength",title="Leveling nudge",text="A quiet reminder to use racials and cooldowns while you level."},
        {icon="Ability_Rogue_Sprint",title="Move elements",text="One click on the main menu to drag all your on-screen elements at once."},
        {icon="INV_Misc_Coin_02",title="Sell white gear",text="Auto-sell can also sell plain white weapons and armor. Tools are kept."},
        {icon="INV_Misc_ArmorKit_17",title="More skin areas",text="Pet frame, party frames, personal resources and cast bars get dark mode."},
        {icon="Spell_Holy_WordFortitude",title="Brighter class colors",text="Player, target and focus bars in the true class color."},
        {icon="INV_Misc_PocketWatch_01",title="Cleaner flight timer",text="One line: the countdown, then where you land."},
    }},
    {version="0.14.7",notes={
        {icon="Ability_Warrior_DefensiveStance",title="Threat meter",text="Your group's threat, styled like and placed next to the damage meter."},
        {icon="Ability_Warrior_DefensiveStance",title="Threat % above target",text="Your threat on the target portrait, with font and background options."},
        {icon="Trade_Engineering",title="Tidier menus",text="Combat and Keybinds on the main menu, Merchant in System; help moved to tooltips and (i) icons."},
        {icon="INV_Misc_PocketWatch_01",title="Lighter in combat",text="Much less work during, after and between fights."},
        {icon="Spell_Nature_TimeStop",title="Cooldown reminders",text="A nudge to use racials, trinkets and big cooldowns on elites and big pulls."},
        {icon="INV_Misc_Key_03",title="Smart interact key",text="One key for RestedXP quest items, targets and Interact with target."},
        {icon="Spell_Fire_Fire",title="Standing in fire",text="A warning sound when you keep taking fire-like damage. Just turn it on."},
        {icon="INV_Inscription_Tradeskill01",title="Meter fonts",text="Pick fonts for the threat meter and the game's damage meter in Fonts."},
    }},
    {version="0.14.6",notes={
        {icon="Ability_Hunter_SniperShot",title="Rare alerts",text="A glowing notice when a rare shows up. Click it to target. Combat."},
        {icon="INV_Misc_Book_09",title="Easier renaming",text="Rename sits with Load, Save and Delete and shows the name you change."},
    }},
    {version="0.14.5",notes={
        {icon="INV_Misc_ArmorKit_17",title="Skin templates",text="Save your own look in Skins and switch between templates any time."},
        {icon="Spell_Holy_WordFortitude",title="Softer aura borders",text="Buffs and debuffs get the same rounded frame as your action buttons."},
        {icon="INV_Misc_PocketWatch_01",title="Tidier leveling stats",text="Label first on every line, so the rows line up."},
        {icon="Trade_Engineering",title="Fixes",text="Hidden quest tracker in combat, save prompt without changes, tooltip page text."},
    }},
    {version="0.14.4",notes={
        {icon="INV_Misc_Book_09",title="Rename profiles",text="Give a profile a new name in the Profiles panel."},
        {icon="INV_Misc_Note_01",title="Macros stay on your bars",text="Profiles remember where your macros sit, for each class."},
        {icon="INV_Misc_EngGizmos_20",title="Make room, hide macros",text="Pick what to delete when Add all doesn't fit. Hide the ones you never use."},
        {icon="Ability_Shaman_Stormstrike",title="Smarter macros",text="Better auto attack and mouseover choices, icons for unlearned spells, Stormstrike."},
        {icon="INV_Misc_Book_11",title="Fresh look, tidier menus",text="Subtle new styling, an even main menu, and settings in clearer places."},
        {icon="INV_Misc_PocketWatch_01",title="More control, less load",text="Buff notice timer, leveling sliders, quest objectives on login. Lighter and faster."},
    }},
    {version="0.14.3",notes={
        "New: quick keybind mode. Type /kb (or System > Gameplay), hover a slot and press a key to bind it; Escape on a bound slot unbinds it.",
        "A snapshot of your keybinds is taken first. Take more while you edit, revert to any of them, then save or discard.",
        "New: tooltip layout builder. Turn the name, guild, level, race, class, faction and target parts on or off, order them, and put them on the same or a new line, with a live preview (Tooltip).",
        "Tooltip faction icon can now go before or after the name or guild, and shows even for players without a guild.",
        "New: Faster looting (System > Gameplay). With auto loot on, everything is looted the moment you open a corpse. Off by default.",
        "New: Restore keybinds (System > Gameplay) lists your last 10 keybind sessions. Hover one to see exactly what it changed; choose it to go back to the keybinds from before it.",
        "Profiles panel: more room between controls, clearer icons, and long profile names wrap onto two lines.",
        "New FT logo, and the minimap button now uses the same round border as other addons' buttons.",
        "Clearer, shorter tooltips and help texts across the addon. The export window explains what carries over after updates.",
        "Macros: Add all adds spells you know first, then by the level you learn them, so a full macro tab only leaves out later spells. You see which ones are left out, and can hover the status line afterwards.",
        "Font manager and Skins: the list scrollbar no longer touches the settings next to it.",
        "Buff reminders page: a clearer two-column layout with sections — start with your own buffs on the left; group, low-rank and look options are on the right.",
    }},
    {version="0.14.2",notes={
        "New: dispel glow. A colored outline on player, target, focus, party or raid-style frames while they have a debuff you can remove (Fonts & colors > Unitframe colors). Off by default.",
        "New: profile exports can include all your keybinds, and importing applies them (Profiles > Export / Import).",
        "Mouse-wheel binding is now deliberate: click a spell in Custom keybinds, then scroll to bind it. Scrolling the list only pages it.",
        "New characters now ask whether to use a saved profile or start a new one.",
        "New: optional rounded background for leveling stats, with color and transparency.",
        "Buff reminders: choose where self and group notices appear — open world, cities, dungeons, raids and PvP.",
        "Every popup now has the same close button.",
        "Fixes: no more gap in the dark-mode target health bar next to the portrait, and XP per hour starts with your first kill.",
    }},
    {version="0.13.6",notes={
        "Everything now starts off on new installs, so the game looks like Blizzard's until you choose otherwise. Existing setups are unchanged.",
        "New: a short first-time setup with Minimal, Dark mode and Full presets. Run it again from System > General.",
        "New: new characters automatically use your profile. Choose which one in Profiles > New characters. New profiles start from default settings, and Profiles > Default settings returns everything to Blizzard's defaults.",
        "Mouse-wheel casting on mouseover (Custom keybinds) now works; away from a unit the wheel still zooms the camera.",
        "New: leveling stats with XP per hour, time to level, kills to level, XP and rested XP. Choose which to show, their order, and one per line or all on one line (System > Gameplay).",
        "New: an optional low-rank marker on action bars, with per-spell exceptions (Buff reminders).",
        "New: auto-sell grey items and auto-repair, each opt-in (System > Gameplay).",
        "New: clickable links in chat that open a copy box (Chat).",
        "New: search settings from the /ft home window.",
        "New: copy a bug report from System > Troubleshooting.",
        "Guild names in player tooltips are plain white by default; faction colors are an option on the Tooltip page.",
        "System is now split into General, Minimap, Gameplay and Troubleshooting. Tooltip IDs moved to the Tooltip page.",
        "Fixes: totem bar dark mode, weapon-enchant buff borders, weapon buff reminder, grouped minimap buttons and the target health bar.",
    }},
}
