local _,FT=...
-- Names verified against the Forever beta ability database; see SPELL_AUDIT.md.
-- One rank is a conservative fallback; the live spellbook supplies learned ranks.
-- Icons are the game's own icon names, used before a spell is learned. An
-- unknown name falls back safely (the macro builder checks it exists).
FT.verifiedMacros={
    Druid={
        {"Mark of the Wild",1,"friendly","spell_nature_regeneration"},
        {"Thorns",1,"friendly","spell_nature_thorns"},
        {"Revive",1,"friendly","INV_Misc_Book_09"},
        {"Cure Poison",1,"friendly","spell_nature_nullifypoison"},
        {"Rebirth",1,"friendly","spell_nature_reincarnation"},
        {"Wrath",1,nil,"spell_nature_abolishmagic"},
        {"Growl",1,"startattack","ability_physical_taunt"},
        {"Hibernate",1,nil,"spell_nature_sleep"},
        {"Claw",1,"startattack","ability_druid_rake"},
        {"Insect Swarm",1,nil,"spell_nature_insectswarm"},
        {"Starfire",1,nil,"spell_arcane_starfire"},
        {"Demoralizing Roar",1,"self","ability_druid_demoralizingroar"},
        {"Nature's Grasp",1,"self","spell_nature_natureswrath"},
        {"Teleport: Moonglade",1,"self","spell_arcane_teleportmoonglade"},
        {"Enrage",1,"self","ability_druid_enrage"},
        {"Aquatic Form",1,"self","ability_druid_aquaticform"},
    },
    Hunter={
        {"Auto Shot",1,nil,"ability_whirlwind"},
        {"Hunter's Mark",1,nil,"ability_hunter_snipershot"},
        {"Tame Beast",1,nil,"ability_hunter_beasttaming"},
        {"Distracting Shot",1,nil,"spell_arcane_blink"},
        {"Scare Beast",1,nil,"ability_druid_cower"},
        {"Disengage",1,nil,"ability_rogue_feint"},
        {"Track Beasts",1,"self","ability_tracking"},
        {"Aspect of the Monkey",1,"self","ability_hunter_aspectofthemonkey"},
        {"Beast Training",1,"self","ability_hunter_beasttraining"},
        {"Call Pet",1,"self","ability_hunter_beastcall"},
        {"Dismiss Pet",1,"self","spell_nature_spiritwolf"},
        {"Feed Pet",1,"self","ability_hunter_beasttraining"},
        {"Revive Pet",1,"self","ability_hunter_beastsoothe"},
        {"Track Humanoids",1,"self","spell_holy_prayerofhealing"},
        {"Mend Pet",1,"self","ability_hunter_mendpet"},
        {"Eagle Eye",1,"self","ability_hunter_eagleeye"},
        {"Eyes of the Beast",1,"self","ability_eyeoftheowl"},
        {"Immolation Trap",1,"self","spell_fire_flameshock"},
        {"Track Undead",1,"self","spell_shadow_darksummoning"},
    },
    Mage={
        {"Arcane Intellect",1,"friendly","spell_holy_magicalsentry"},
        {"Dampen Magic",1,"friendly","spell_nature_abolishmagic"},
        {"Amplify Magic",1,"friendly","spell_holy_flashheal"},
        {"Remove Lesser Curse",1,"friendly","spell_nature_removecurse"},
        {"Arcane Blast",1,nil,"spell_arcane_blast"},
        {"Ice Lance",1,nil,"spell_frost_frostblast"},
        {"Pyroblast",1,nil,"spell_fire_fireball02"},
        {"Frost Armor",1,"self","spell_frost_frostarmor02"},
        {"Conjure Water",1,"self","inv_drink_06"},
        {"Conjure Food",1,"self","inv_misc_food_10"},
        {"Study",1,"self","INV_Misc_Book_09"},
        {"Slow Fall",1,"self","spell_magic_featherfall"},
        {"Arcane Explosion",1,"self","spell_nature_wispsplode"},
        {"Flamestrike",1,"self","spell_fire_selfdestruct"},
        {"Blizzard",1,"self","spell_frost_icestorm"},
        {"Evocation",1,"self","spell_nature_purge"},
        {"Fire Ward",1,"self","spell_fire_firearmor"},
        {"Teleport: Ironforge",1,"self","spell_arcane_teleportironforge"},
        {"Teleport: Orgrimmar",1,"self","spell_arcane_teleportorgrimmar"},
        {"Teleport: Stormwind",1,"self","spell_arcane_teleportstormwind"},
        {"Teleport: Undercity",1,"self","spell_arcane_teleportundercity"},
    },
    Paladin={
        {"Exorcism",1,nil,"spell_holy_excorcism_02"},
        {"Devotion Aura",1,"self","spell_holy_devotionaura"},
        {"Divine Protection",1,"self","spell_holy_restoration"},
        {"Seal of the Crusader",1,"self","spell_holy_holysmite"},
        {"Seal of Fury",1,"self","INV_Misc_Book_09"},
        {"Retribution Aura",1,"self","spell_holy_auraoflight"},
        {"Righteous Fury",1,"self","spell_holy_sealoffury"},
        {"Sense Undead",1,"self","spell_holy_senseundead"},
    },
    Priest={
        {"Power Word: Fortitude",1,"friendly","spell_holy_wordfortitude"},
        {"Fear Ward",1,"friendly","spell_holy_excorcism"},
        {"Smite",1,nil,"spell_holy_holysmite"},
        {"Confounding Flash",1,nil,"INV_Misc_Book_09"},
        {"Hex of Weakness",1,nil,"spell_shadow_fingerofdeath"},
        {"Starshards",1,nil,"spell_arcane_starfire"},
        {"Chastise",1,nil,"INV_Misc_Book_09"},
        {"Devouring Plague",1,nil,"spell_shadow_blackplague"},
        {"Holy Fire",1,nil,"spell_holy_searinglight"},
        {"Mind Soothe",1,nil,"spell_holy_mindsooth"},
        {"Shackle Undead",1,nil,"spell_nature_slow"},
        {"Fade",1,"self","spell_magic_lesserinvisibilty"},
        {"Desperate Prayer",1,"self","spell_holy_restoration"},
        {"Divine Grace",1,"self","INV_Misc_Book_09"},
        {"Touch of Weakness",1,"self","spell_shadow_deadofnight"},
        {"Inner Fire",1,"self","spell_holy_innerfire"},
        {"Contingency Plan",1,"self","INV_Misc_Book_09"},
        {"Dark Sacrifice",1,"self","INV_Misc_Book_09"},
        {"Elune's Grace",1,"self","spell_holy_elunesgrace"},
        {"Feedback",1,"self","spell_shadow_ritualofsacrifice"},
        {"Holy Nova",1,"self","spell_holy_holynova"},
        {"Shadowguard",1,"self","spell_nature_lightningshield"},
    },
    Rogue={
        {"Pick Pocket",1,nil,"inv_misc_bag_11"},
        {"Expose Armor",1,"startattack","ability_warrior_riposte"},
        {"Feint",1,nil,"ability_rogue_feint"},
        {"Pick Lock",1,"self","spell_nature_moonkey"},
        {"Slice and Dice",1,"self","ability_rogue_slicedice"},
        {"Poisons",1,"self","INV_Misc_Book_09"},
        {"Crippling Poison",1,"self","INV_Misc_Book_09"},
        {"Instant Poison",1,"self","INV_Misc_Book_09"},
    },
    Shaman={
        {"Ancestral Spirit",1,"friendly","spell_nature_regenerate"},
        {"Cure Poison",1,"friendly","spell_nature_nullifypoison"},
        {"Rockbiter Weapon",1,"self","spell_nature_rockbiter"},
        {"Stoneskin Totem",1,"self","spell_nature_stoneskintotem"},
        {"Earthbind Totem",1,"self","spell_nature_strengthofearthtotem02"},
        {"Stoneclaw Totem",1,"self","spell_nature_stoneclawtotem"},
        {"Flametongue Weapon",1,"self","spell_fire_flametounge"},
        {"Searing Totem",1,"self","spell_fire_searingtotem"},
        {"Strength of Earth Totem",1,"self","spell_nature_earthbindtotem"},
        {"Fire Nova",1,"self","spell_fire_sealoffire"},
        {"Tremor Totem",1,"self","spell_nature_tremortotem"},
        {"Call of the Elements",1,"self","INV_Misc_Book_09"},
        {"Frostbrand Weapon",1,"self","spell_frost_frostbrand"},
        {"Healing Stream Totem",1,"self","inv_spear_04"},
        {"Totemic Recall",1,"self","spell_shaman_totemrecall"},
    },
    Warlock={
        {"Curse of Weakness",1,nil,"spell_shadow_curseofmannoroth"},
        {"Bane of Agony",1,nil,"spell_shadow_curseofsargeras"},
        {"Drain Soul",1,nil,"spell_shadow_haunting"},
        {"Curse of Recklessness",1,nil,"spell_shadow_unholystrength"},
        {"Searing Pain",1,nil,"spell_fire_soulburn"},
        {"Curse of the Elements",1,nil,"spell_shadow_chilltouch"},
        {"Shadowburn",1,nil,"spell_shadow_scourgebuild"},
        {"Unending Breath",1,"friendly","spell_shadow_demonbreath"},
        {"Demon Skin",1,"self","spell_shadow_ragingscream"},
        {"Summon Imp",1,"self","spell_shadow_summonimp"},
        {"Create Healthstone",1,"self","inv_stone_04"},
        {"Summon Voidwalker",1,"self","spell_shadow_summonvoidwalker"},
        {"Health Funnel",1,"self","spell_shadow_lifedrain"},
        {"Create Soulstone",1,"self","spell_shadow_soulgem"},
        {"Demon Armor",1,"self","spell_shadow_ragingscream"},
        {"Rain of Fire",1,"self","spell_shadow_rainoffire"},
        {"Ritual of Summoning",1,"self","spell_shadow_twilight"},
        {"Summon Incubus",1,"self","INV_Misc_Book_09"},
        {"Summon Succubus",1,"self","spell_shadow_summonsuccubus"},
    },
    Warrior={
        {"Taunt",1,"startattack","spell_nature_reincarnation"},
        {"Victory Rush",1,"startattack","ability_warrior_devastate"},
        {"Battle Shout",1,"self","ability_warrior_battleshout"},
        {"Battle Stance",1,"self","ability_warrior_offensivestance"},
        {"Bloodrage",1,"self","ability_racial_bloodrage"},
        {"Defensive Stance",1,"self","ability_warrior_defensivestance"},
        {"Demoralizing Shout",1,"self","ability_warrior_warcry"},
        {"Shield Block",1,"self","ability_defend"},
        {"Retaliation",1,"self","ability_warrior_challange"},
    },
}
