local _,FT=...
-- Names verified against the Forever beta ability database; see SPELL_AUDIT.md.
-- One rank is a conservative fallback; the live spellbook supplies learned ranks.
FT.verifiedMacros={
    Druid={
        {"Mark of the Wild",1,"friendly","INV_Misc_Book_09"},
        {"Thorns",1,"friendly","INV_Misc_Book_09"},
        {"Revive",1,"friendly","INV_Misc_Book_09"},
        {"Cure Poison",1,"friendly","INV_Misc_Book_09"},
        {"Rebirth",1,"friendly","INV_Misc_Book_09"},
        {"Wrath",1,nil,"INV_Misc_Book_09"},
        {"Growl",1,nil,"INV_Misc_Book_09"},
        {"Hibernate",1,nil,"INV_Misc_Book_09"},
        {"Claw",1,nil,"INV_Misc_Book_09"},
        {"Insect Swarm",1,nil,"INV_Misc_Book_09"},
        {"Starfire",1,nil,"INV_Misc_Book_09"},
        {"Demoralizing Roar",1,"self","INV_Misc_Book_09"},
        {"Nature's Grasp",1,"self","INV_Misc_Book_09"},
        {"Teleport: Moonglade",1,"self","INV_Misc_Book_09"},
        {"Enrage",1,"self","INV_Misc_Book_09"},
        {"Aquatic Form",1,"self","INV_Misc_Book_09"},
    },
    Hunter={
        {"Auto Shot",1,nil,"INV_Misc_Book_09"},
        {"Hunter's Mark",1,nil,"INV_Misc_Book_09"},
        {"Tame Beast",1,nil,"INV_Misc_Book_09"},
        {"Distracting Shot",1,nil,"INV_Misc_Book_09"},
        {"Scare Beast",1,nil,"INV_Misc_Book_09"},
        {"Disengage",1,nil,"INV_Misc_Book_09"},
        {"Track Beasts",1,"self","INV_Misc_Book_09"},
        {"Aspect of the Monkey",1,"self","INV_Misc_Book_09"},
        {"Beast Training",1,"self","INV_Misc_Book_09"},
        {"Call Pet",1,"self","INV_Misc_Book_09"},
        {"Dismiss Pet",1,"self","INV_Misc_Book_09"},
        {"Feed Pet",1,"self","INV_Misc_Book_09"},
        {"Revive Pet",1,"self","INV_Misc_Book_09"},
        {"Track Humanoids",1,"self","INV_Misc_Book_09"},
        {"Mend Pet",1,"self","INV_Misc_Book_09"},
        {"Eagle Eye",1,"self","INV_Misc_Book_09"},
        {"Eyes of the Beast",1,"self","INV_Misc_Book_09"},
        {"Immolation Trap",1,"self","INV_Misc_Book_09"},
        {"Track Undead",1,"self","INV_Misc_Book_09"},
    },
    Mage={
        {"Arcane Intellect",1,"friendly","INV_Misc_Book_09"},
        {"Dampen Magic",1,"friendly","INV_Misc_Book_09"},
        {"Amplify Magic",1,"friendly","INV_Misc_Book_09"},
        {"Remove Lesser Curse",1,"friendly","INV_Misc_Book_09"},
        {"Arcane Blast",1,nil,"INV_Misc_Book_09"},
        {"Ice Lance",1,nil,"INV_Misc_Book_09"},
        {"Pyroblast",1,nil,"INV_Misc_Book_09"},
        {"Frost Armor",1,"self","INV_Misc_Book_09"},
        {"Conjure Water",1,"self","INV_Misc_Book_09"},
        {"Conjure Food",1,"self","INV_Misc_Book_09"},
        {"Study",1,"self","INV_Misc_Book_09"},
        {"Slow Fall",1,"self","INV_Misc_Book_09"},
        {"Arcane Explosion",1,"self","INV_Misc_Book_09"},
        {"Flamestrike",1,"self","INV_Misc_Book_09"},
        {"Blizzard",1,"self","INV_Misc_Book_09"},
        {"Evocation",1,"self","INV_Misc_Book_09"},
        {"Fire Ward",1,"self","INV_Misc_Book_09"},
        {"Teleport: Ironforge",1,"self","INV_Misc_Book_09"},
        {"Teleport: Orgrimmar",1,"self","INV_Misc_Book_09"},
        {"Teleport: Stormwind",1,"self","INV_Misc_Book_09"},
        {"Teleport: Undercity",1,"self","INV_Misc_Book_09"},
    },
    Paladin={
        {"Exorcism",1,nil,"INV_Misc_Book_09"},
        {"Devotion Aura",1,"self","INV_Misc_Book_09"},
        {"Divine Protection",1,"self","INV_Misc_Book_09"},
        {"Seal of the Crusader",1,"self","INV_Misc_Book_09"},
        {"Seal of Fury",1,"self","INV_Misc_Book_09"},
        {"Retribution Aura",1,"self","INV_Misc_Book_09"},
        {"Righteous Fury",1,"self","INV_Misc_Book_09"},
        {"Sense Undead",1,"self","INV_Misc_Book_09"},
    },
    Priest={
        {"Lesser Heal",1,"friendly","INV_Misc_Book_09"},
        {"Power Word: Fortitude",1,"friendly","INV_Misc_Book_09"},
        {"Fear Ward",1,"friendly","INV_Misc_Book_09"},
        {"Smite",1,nil,"INV_Misc_Book_09"},
        {"Confounding Flash",1,nil,"INV_Misc_Book_09"},
        {"Hex of Weakness",1,nil,"INV_Misc_Book_09"},
        {"Starshards",1,nil,"INV_Misc_Book_09"},
        {"Chastise",1,nil,"INV_Misc_Book_09"},
        {"Devouring Plague",1,nil,"INV_Misc_Book_09"},
        {"Holy Fire",1,nil,"INV_Misc_Book_09"},
        {"Mind Soothe",1,nil,"INV_Misc_Book_09"},
        {"Shackle Undead",1,nil,"INV_Misc_Book_09"},
        {"Fade",1,"self","INV_Misc_Book_09"},
        {"Desperate Prayer",1,"self","INV_Misc_Book_09"},
        {"Divine Grace",1,"self","INV_Misc_Book_09"},
        {"Touch of Weakness",1,"self","INV_Misc_Book_09"},
        {"Inner Fire",1,"self","INV_Misc_Book_09"},
        {"Contingency Plan",1,"self","INV_Misc_Book_09"},
        {"Dark Sacrifice",1,"self","INV_Misc_Book_09"},
        {"Elune's Grace",1,"self","INV_Misc_Book_09"},
        {"Feedback",1,"self","INV_Misc_Book_09"},
        {"Holy Nova",1,"self","INV_Misc_Book_09"},
        {"Shadowguard",1,"self","INV_Misc_Book_09"},
    },
    Rogue={
        {"Pick Pocket",1,nil,"INV_Misc_Book_09"},
        {"Expose Armor",1,nil,"INV_Misc_Book_09"},
        {"Feint",1,nil,"INV_Misc_Book_09"},
        {"Pick Lock",1,"self","INV_Misc_Book_09"},
        {"Slice and Dice",1,"self","INV_Misc_Book_09"},
        {"Poisons",1,"self","INV_Misc_Book_09"},
        {"Crippling Poison",1,"self","INV_Misc_Book_09"},
        {"Instant Poison",1,"self","INV_Misc_Book_09"},
    },
    Shaman={
        {"Ancestral Spirit",1,"friendly","INV_Misc_Book_09"},
        {"Cure Poison",1,"friendly","INV_Misc_Book_09"},
        {"Rockbiter Weapon",1,"self","INV_Misc_Book_09"},
        {"Stoneskin Totem",1,"self","INV_Misc_Book_09"},
        {"Earthbind Totem",1,"self","INV_Misc_Book_09"},
        {"Stoneclaw Totem",1,"self","INV_Misc_Book_09"},
        {"Flametongue Weapon",1,"self","INV_Misc_Book_09"},
        {"Searing Totem",1,"self","INV_Misc_Book_09"},
        {"Strength of Earth Totem",1,"self","INV_Misc_Book_09"},
        {"Fire Nova",1,"self","INV_Misc_Book_09"},
        {"Tremor Totem",1,"self","INV_Misc_Book_09"},
        {"Call of the Elements",1,"self","INV_Misc_Book_09"},
        {"Frostbrand Weapon",1,"self","INV_Misc_Book_09"},
        {"Healing Stream Totem",1,"self","INV_Misc_Book_09"},
        {"Totemic Recall",1,"self","INV_Misc_Book_09"},
    },
    Warlock={
        {"Curse of Weakness",1,nil,"INV_Misc_Book_09"},
        {"Bane of Agony",1,nil,"INV_Misc_Book_09"},
        {"Drain Soul",1,nil,"INV_Misc_Book_09"},
        {"Curse of Recklessness",1,nil,"INV_Misc_Book_09"},
        {"Searing Pain",1,nil,"INV_Misc_Book_09"},
        {"Curse of the Elements",1,nil,"INV_Misc_Book_09"},
        {"Shadowburn",1,nil,"INV_Misc_Book_09"},
        {"Unending Breath",1,"friendly","INV_Misc_Book_09"},
        {"Demon Skin",1,"self","INV_Misc_Book_09"},
        {"Summon Imp",1,"self","INV_Misc_Book_09"},
        {"Create Healthstone",1,"self","INV_Misc_Book_09"},
        {"Summon Voidwalker",1,"self","INV_Misc_Book_09"},
        {"Health Funnel",1,"self","INV_Misc_Book_09"},
        {"Create Soulstone",1,"self","INV_Misc_Book_09"},
        {"Demon Armor",1,"self","INV_Misc_Book_09"},
        {"Rain of Fire",1,"self","INV_Misc_Book_09"},
        {"Ritual of Summoning",1,"self","INV_Misc_Book_09"},
        {"Summon Incubus",1,"self","INV_Misc_Book_09"},
        {"Summon Succubus",1,"self","INV_Misc_Book_09"},
    },
    Warrior={
        {"Taunt",1,nil,"INV_Misc_Book_09"},
        {"Victory Rush",1,nil,"INV_Misc_Book_09"},
        {"Battle Shout",1,"self","INV_Misc_Book_09"},
        {"Battle Stance",1,"self","INV_Misc_Book_09"},
        {"Bloodrage",1,"self","INV_Misc_Book_09"},
        {"Defensive Stance",1,"self","INV_Misc_Book_09"},
        {"Demoralizing Shout",1,"self","INV_Misc_Book_09"},
        {"Shield Block",1,"self","INV_Misc_Book_09"},
        {"Retaliation",1,"self","INV_Misc_Book_09"},
    },
}
